spring:
  datasource:
    url: jdbc:mysql://${SHOP_EASE_DB_IP:localhost}:${SHOP_EASE_DB_PORT:3306}/shop_ease
    username: ${SHOP_EASE_DB_USERNAME:root}
    password: ${SHOP_EASE_DB_PASSWORD:root123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  sql:
    init:
      mode:
